[uat-webservers]
172.31.32.136 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file='/var/lib/jenkins/workspace/save_artifacts/home/ubuntu/ansible-config-artifact/Mary.pem'
172.31.39.80 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file='/var/lib/jenkins/workspace/save_artifacts/home/ubuntu/ansible-config-artifact/Mary.pem'

