pipeline {
    agent any

  environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }
  parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

stages {
        stage('SCM checkout') {
            steps {
                git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/genejike/ansible-config-mgt'
            }
        }

      stage('Prepare Ansible For Execution') {
        steps {
          sh "echo ${WORKSPACE}"
          sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'  
        }
     }
    
   
      stage('run ansible playbooks') {
            steps {
              ansiblePlaybook become: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible2', inventory: 'inventory/dev', playbook: 'playbooks/site.yml' 
            }
        }
    
    
        stage('cleaning after build') {
            steps {
              cleanWs()
            }
        }
    }

}
