  pipeline {
    agent any


  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }


  stage('Test') {
  steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }

 stage('Package') {
  steps {
        script {
          sh 'echo "Packaging Stage"'
        }
      }
    }

stage('deploy'){
  steps{
    script{
      sh 'echo "Deploy stage"'
    }
  }
}


stage('clean_up'){
  staeps{
    script{

      sh'"Cleaning stage"'
    }
  }
}


    }
}
