- hosts: all
  name: import dynamic variables
  tasks:
      import_playbook: ../static-assignments/common.yml
      import_playbook: ../dynamic-assignments/env-vars.yml
      tags:
        - always


- hosts: webservers
  tasks:
    - name: Webserver assignment
      import_playbook: ../static-assignments/webservers.yml

- hosts: lb
  tasks:
    - name: Loadbalancers assignment
      import_playbook: ../static-assignments/loadbalancers.yml
      when: load_balancer_is_required
